# CAD Preload Plugin for Fabrikator
# Provides library documentation, tutorials, and examples for CAD agents
#
# Assets are bundled with the plugin in the assets/ folder:
# - assets/tutorials/*.md  - Library tutorials
# - assets/examples/*.scad - Code examples

plugin:
  id: cad-preload
  slug: cad-preload
  name: CAD Library Preload
  author: Fabrikator Team
  authorEmail: support@fabrikator.io
  description: |
    Preloads CAD library documentation, tutorials, and examples directly into 
    the agent's context. This helps the agent write better OpenSCAD code by 
    providing immediate access to library references without search calls.
    
    Currently includes:
    - BOSL2 (Belfry OpenSCAD Library v2) quick reference
    - BOSL2 tutorials and guides
    - BOSL2 code examples
    - Common library list (threads-scad, dotSCAD, Round-Anything, NopSCADlib)
    
    Features:
    - Quick reference for common patterns
    - Full tutorials loaded from plugin assets
    - Code examples loaded from plugin assets
    - Reduces need for search_docs calls for common operations
  shortDescription: CAD library tutorials and examples for better code generation
  categories:
    - cad
    - documentation
    - libraries
  keywords:
    - bosl2
    - openscad
    - library
    - tutorials
    - examples
    - preload
  iconUrl: https://fabrikator.ai/icons/cad-preload.png

requirements:
  minPlatformVersion: "1.0.0"

capabilities:
  prompts:
    agents:
      # Quick reference (static, small)
      - agent: cad
        position: append
        priority: 10
        content: |
          ## AVAILABLE OPENSCAD LIBRARIES
          
          The following libraries are installed and available for use:
          - **BOSL2** (Belfry OpenSCAD Library v2) - Comprehensive library with enhanced primitives
          - **threads-scad** - Thread generation library
          - **dotSCAD** - Functional OpenSCAD library
          - **Round-Anything** - Fillets and rounding library
          - **NopSCADlib** - Vitamins and printed parts library

          ## MANDATORY LIBRARY USAGE RULES
          - ❌ **NEVER use vanilla \`cylinder()\`** → ✅ **ALWAYS use BOSL2 \`cyl()\`** (supports \`anchor=\`, \`orient=\`)
          - ❌ **NEVER use vanilla \`cube()\`** → ✅ **ALWAYS use BOSL2 \`cuboid()\`** (supports \`anchor=\`, rounding)
          - ❌ **NEVER use \`translate([x,0,0])\`** → ✅ **ALWAYS use BOSL2 \`right(x)\`** (or \`left()\`, \`fwd()\`, \`back()\`, \`up()\`, \`down()\`)
          - ❌ **NEVER use \`translate() + rotate() + cylinder()\`** → ✅ **ALWAYS use \`cyl()\` with \`anchor=\` and \`orient=\`**
          - ❌ **NEVER manually position connected parts** → ✅ **ALWAYS use BOSL2 \`attach(SIDE)\`** to connect objects
          - ❌ **NEVER use vanilla \`rotate([a,b,c])\` for orientation** → ✅ **ALWAYS use BOSL2 \`orient=\` parameter or \`xrot()\`, \`yrot()\`, \`zrot()\`**
  
          ## PERFORMANCE OPTIMIZATION (⚠️ CRITICAL - READ THIS)
            Complex geometry can cause renders to take HOURS or TIME OUT. Avoid these patterns:

            **FORBIDDEN OPERATIONS (will cause timeout):**
            - \`minkowski()\` - O(n*m) complexity, NEVER use with spheres or high-poly objects
            - \`hull()\` on many objects - exponential complexity, use \`hull_objects()\` instead
            - Multiple nested CSG operations on minkowski results - use \`minkowski_union()\` instead
            - \`$fn = 64\` or higher on curved surfaces - use \`$fn = 24\` or lower
          
            **✅ USE INSTEAD:**
            - For fillets/rounds: Use BOSL2 \`rounding=\` parameter on \`cuboid()\`, \`cyl()\`, etc.
            - For pipe bends: Use BOSL2 \`path_sweep()\` or \`tube()\` with \`path=\`
            - For smooth curves: Keep \`$fn <= 32\`, use \`$fn = $preview ? 16 : 32\`
            - For complex shapes: Break into simple primitives with \`union()\`

            1. **Use adaptive $fn based on context:**
              \`\`\`openscad
              // RECOMMENDED: Lower resolution during development, full resolution for export
              $fn = $preview ? 16 : 32;  // 16 for preview/validation, 32 for final 3MF
              \`\`\`

            2. **For threaded holes specifically:**
              - Threads are computationally expensive (helical geometry with many facets)
              - Use \`$fn = 16\` or lower during development
              - Only increase to \`$fn = 32\` for final export if thread quality matters
              - Consider: do you REALLY need actual threads? For visualization, a simple cylinder with slightly smaller diameter often suffices

            3. **General $fn guidelines:**
              - \`$fn = 16\` - Fast preview, acceptable for most prototyping
              - \`$fn = 24\` - Good balance of quality and speed
              - \`$fn = 32\` - High quality, noticeably slower for complex models
              - \`$fn = 64+\` - ⛔ FORBIDDEN during development, causes timeouts

            4. **Place $fn at file top** so it affects all geometry:
              \`\`\`openscad
              // At the top of your SCAD file
              $fn = $preview ? 16 : 32;
              
              include <BOSL2/std.scad>
              // ... rest of code
              \`\`\`

          **BOSL2 PIPE AND TUBE EXAMPLES** (⚠️ CRITICAL FOR PLUMBING/PIPING PROJECTS)
   
          **For hollow pipes and tubes**, ALWAYS use BOSL2's dedicated functions:
          
          **Simple straight hollow tube:**
          \`\`\`openscad
          include <BOSL2/std.scad>
          $fn = $preview ? 16 : 32;
          
          // tube() creates a hollow cylinder directly - NO difference() needed!
          tube(h=50, od=13, id=9, anchor=BOTTOM);  // 2mm wall thickness
          \`\`\`
          
          **90-degree elbow pipe (HOLLOW):**
          \`\`\`openscad
          include <BOSL2/std.scad>
          $fn = $preview ? 16 : 32;
          
          id = 9;   // inner diameter
          od = 13;  // outer diameter (2mm wall)
          bend_r = 15;  // bend radius to centerline
          
          // Use path_sweep with a hollow circle profile (region)
          // Step 1: Create 2D hollow circle as a region (NOT a module!)
          hollow_profile = difference(circle(d=od), circle(d=id));
          
          // Step 2: Create the 3D path (arc for the bend)
          bend_path = arc(n=17, r=bend_r, angle=[0, 90]);  // 17 points for smooth curve
          
          // Step 3: Sweep the hollow profile along the path
          path_sweep(hollow_profile, bend_path);
          \`\`\`
          
          **90-degree elbow with straight legs:**
          \`\`\`openscad
          include <BOSL2/std.scad>
          $fn = $preview ? 16 : 32;
          
          id = 9; od = 13;
          bend_r = 15;
          leg1_len = 40;  // longer leg
          leg2_len = 20;  // shorter leg
          
          hollow_profile = difference(circle(d=od), circle(d=id));
          
          // Build full path: straight → arc → straight
          // Use BOSL2 path functions for correct concatenation
          path = concat(
            [for (z = [0 : 5 : leg1_len]) [0, 0, z]],  // Leg 1 going up
            arc(n=17, r=bend_r, angle=[0, 90], cp=[bend_r, 0, leg1_len]),  // Arc bend
            [for (y = [0 : 5 : leg2_len]) [bend_r + y, 0, leg1_len + bend_r]]  // Leg 2 going right
          );
          
          path_sweep(hollow_profile, path);
          \`\`\`
          
          **Adding a flange to the elbow:**
          \`\`\`openscad
          include <BOSL2/std.scad>
          $fn = $preview ? 16 : 32;
          
          module elbow_with_flange() {
            id = 9; od = 13; bend_r = 15;
            flange_d = 25; flange_t = 2;
            
            union() {
              // The elbow pipe (use path_sweep as shown above)
              color("white") elbow_pipe();
              
              // The flange - simple disc with hole
              color("white")
              translate([0, 0, 5])  // Position near the bend
              difference() {
                cyl(d=flange_d, h=flange_t, anchor=CENTER);
                cyl(d=od + 0.1, h=flange_t + 1, anchor=CENTER);  // Hole for pipe
              }
            }
          }\`\`\`

           **⚠️ COMMON MISTAKES TO AVOID:**
            - ❌ \`difference() { cylinder(); cylinder(); }\` - Don't use vanilla primitives for hollow shapes
            - ❌ Creating 2D profile as a module instead of a variable - \`path_sweep\` needs a shape, not a module
            - ❌ Using Python-style list slicing \`list[0:5]\` - OpenSCAD uses \`[for (i=[0:4]) list[i]]\`
            - ❌ Trying to use \`return\` statements - OpenSCAD doesn't have return
            - ❌ Using \`arc_points()\` - The correct function is \`arc()\`
            
            **✅ KEY PATTERNS:**
            - Use \`tube()\` for simple hollow cylinders
            - Use \`path_sweep(profile, path)\` for pipes following complex paths
            - Create 2D profiles as variables: \`profile = circle(d=10);\` NOT as modules
            - Use \`arc(n=N, r=R, angle=[start, end])\` to create arc paths
            - Use \`concat()\` to join path segments, NOT list slicing
          
          ## BOSL2 QUICK REFERENCE
          
          ### Core Primitives (ALWAYS use these instead of vanilla OpenSCAD)
          ```scad
          // Instead of cylinder() use:
          cyl(h=10, d=5, rounding=1);  // Cylinder with rounded edges
          cyl(h=10, d1=5, d2=3);       // Tapered cylinder
          
          // Instead of cube() use:
          cuboid([10, 20, 5], rounding=2);  // Rounded box
          cuboid([10, 20, 5], chamfer=1);   // Chamfered box
          
          // Instead of sphere() use:
          sphere(d=10);  // Same but consistent with BOSL2 style
          ```
          
          ### Attachments (Position parts relative to each other)
          ```scad
          // Attach child to parent's face
          cuboid([20, 20, 5])
            attach(TOP) cyl(h=10, d=5);  // Cylinder on top
          
          // Common attachment points: TOP, BOTTOM, LEFT, RIGHT, FRONT, BACK
          // Edges: TOP+FRONT, BOTTOM+LEFT, etc.
          // Corners: TOP+FRONT+LEFT, etc.
          ```
          
          ### Transformations
          ```scad
          // Position helpers
          up(10) cube(5);      // Move up (Z+)
          down(10) cube(5);    // Move down (Z-)
          left(10) cube(5);    // Move left (X-)
          right(10) cube(5);   // Move right (X+)
          fwd(10) cube(5);     // Move forward (Y+)
          back(10) cube(5);    // Move back (Y-)
          
          // Rotation helpers
          xrot(45) cube(5);    // Rotate around X
          yrot(45) cube(5);    // Rotate around Y
          zrot(45) cube(5);    // Rotate around Z
          ```
          
          ### Pipes and Tubes
          ```scad
          // Hollow cylinder (tube)
          tube(h=20, od=10, id=8);  // Outer diameter 10, inner diameter 8
          
          // Path sweep for complex pipes
          path = [[0,0,0], [50,0,0], [50,50,0], [50,50,50]];
          path_sweep(circle(d=5), path);
          ```
          
          ### Boolean Operations with BOSL2
          ```scad
          // Difference with tags
          diff("hole")
            cuboid([20, 20, 10])
              attach(TOP) tag("hole") cyl(h=15, d=5);
          ```

      # Tutorials (loaded from plugin assets)
      - agent: cad
        position: append
        priority: 15
        content: |
          ## LIBRARY TUTORIALS
          
          The following tutorials provide detailed guidance on using CAD libraries:
        contentFromAssets:
          - path: tutorials/*.md
            wrapper: "### {basename}\n\n{content}"
            separator: "\n\n---\n\n"
            maxFiles: 10  # Limit to avoid context overflow

      # Code examples (loaded from plugin assets)
      - agent: cad
        position: append
        priority: 20
        content: |
          ## CODE EXAMPLES
          
          Study these examples for common library patterns:
        contentFromAssets:
          - path: examples/*.scad
            wrapper: "### {basename}\n\n```scad\n{content}\n```"
            separator: "\n\n"

      # Usage reminders (static)
      - agent: cad
        position: append
        priority: 25
        content: |
          ## LIBRARY USAGE REMINDERS
          
          Before writing any OpenSCAD code:
          1. Use BOSL2 primitives (cyl, cuboid) instead of vanilla (cylinder, cube)
          2. Use attachments for positioning instead of translate()
          3. Use up/down/left/right/fwd/back for simple movements
          4. Use xrot/yrot/zrot for rotations
          5. Use tube() for hollow cylinders, not difference()
          
          If you need more details about a specific library function, use the documentation search plugin.

pricing:
  model: free
